const SELECTTODO = 'SELECTTODO'
const UNSELECTTODO = 'UNSELECTTODO'
const NEXTTODO = 'NEXTTODO'
const PREVTODO = 'PREVTODO'
const DELETETASK = 'DELETETASK'
const TOGGLEEDITING = ' TOGGLEEDITING'

export { SELECTTODO, UNSELECTTODO, NEXTTODO, PREVTODO, DELETETASK, TOGGLEEDITING }